// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxoodcdxscxazjkoqhsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4b29kY2R4c2N4YXpqa29xaHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjEzNDEsImV4cCI6MjA2NTMzNzM0MX0.zIk89FApqssu38EpatZKo-HWXH0i6_Olno2a22pDlC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);